# Deployment script for deployment below.
# Below kubectl code will generate the deployment script for the deployment.
# D:\workspace\kubernetes\currency-exchange-service>kubectl get deployment currency-exchange -o yaml >> deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 2  # how many pods we want
  selector:
    matchLabels:
      app: currency-exchange  # Deployment is applicable for all the pods which have this matching lable
  strategy:
    rollingUpdate:  # how an update, to this deployment is done
      maxSurge: 25%  # how many new instances be created when we are doing release
      maxUnavailable: 25%  # how many instances can be unavailable when we are doing the release
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange  # To entire pod we are attaching the label, so this is the lable that is attached to every container in the pod.
    spec:
      containers:
      - image: placidpj/kubernetes-currency-exchange-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: kubernetes-currency-exchange-service
      restartPolicy: Always # if there is any problem with the container you can restart them.

# Add 3 hyphen(-) below to seperate deployment from service deployment script. 
# Added deployment script for service details below. Below kubectl code will generate the deployment script for the service.
# D:\workspace\kubernetes\currency-exchange-service>kubectl get service currency-exchange -o yaml >> service.yaml
---
apiVersion: v1
kind: Service  # service matches against the deployment.
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default 
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange  # On above ports expose deployment that matches this lables.
  sessionAffinity: None  # For web application we want sessionAffinity because in one session all the requests must go to same instance.
  type: LoadBalancer  # Type of the service we want to use is load balancer.
